# Meta Data for SEO

## Homepage
title = "Melrōse"
titleSeparator = "-"
titleAddition = "Music Programming Language"
description = "a MIDI producing environment for creating (live) music."

## Open Graph + Twitter Cards
images = ["melrose.png"]
#twitterSite = " "
#twitterCreator = " "
#facebookAuthor = " "
#facebookPublisher = " "
ogLocale = "en_US"

## JSON-LD
#schemaType = "Organization"
#schemaLogo = " "
#schemaTwitter = "https://twitter.com/ "
#schemaLinkedIn = "https://www.linkedin.com/in/ /"
#schemaGitHub = "https://github.com/ "
#schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Melrōse? <a class=\"alert-link\" href=\"https://github.com/emicklei/melrose/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/emicklei/melrose-docs"
editPage = true
