tags:
- melrose

steps:
- id: "install modules"
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: "build site"
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','build']  

- id: "update site bucket"
  name: 'gcr.io/cloud-builder/gsutil'
  args: ['-m','rsync','-r','public','gs://melrose-static-website']